### ISSUE TITLE
bug: `RevokeMeteringPointDelegate` does not verify metering point ownership

### ISSUE THREAD

**Issue by LayZeeDK** [Energinet-DataHub/eo-auth#4]
# Expected behavior
Metering point ownership is verified before deleting a metering point delegate.

This might be done by calling `DatabaseController#is_current_owner` or `MeteringPointOwnerQuery#is_current_owner`,

# Actual behavior
`RevokeMeteringPointDelegate` verifies that a metering point delegate exists and deletes it if that is the case
https://github.com/Energy-Track-and-Trace/ett-auth/blob/bf2e1eab0ea9eb52f1b1e3038e15e0a747b5e315/src/auth_api/endpoints/delegates.py#L196-L262

but neither `DatabaseController#meteringpoint_delegate_exists`
https://github.com/Energy-Track-and-Trace/ett-auth/blob/bf2e1eab0ea9eb52f1b1e3038e15e0a747b5e315/src/auth_api/controller.py#L61-L74

nor `DatabaseController#delete_meteringpoint_delegate` https://github.com/Energy-Track-and-Trace/ett-auth/blob/bf2e1eab0ea9eb52f1b1e3038e15e0a747b5e315/src/auth_api/controller.py#L99-L111

verifies metering point ownership.

**Comment by kennethkammersgaard** [comment]
@MartinSchmidt er dette til Eloverblik eller Energioprindelse? Og er den stadig relevant?
